Changed yaml files

diff --git a/.github/workflows/hosting-comment-hoster.yml b/.github/workflows/hosting-comment-hoster.yml
--- a/.github/workflows/hosting-comment-hoster.yml
+++ b/.github/workflows/hosting-comment-hoster.yml
@@ -1,18 +1,26 @@
 name: Hosting hoster
 
-on:
-  issue_comment:
-    types:
-      - created
-      - edited
+on: [push]
 
 jobs:
   validate:
     runs-on: ubuntu-latest
-    if: ${{ github.event.comment.body == '/hosting host' }}
     outputs:
       actor_in_hosting_team: ${{ steps.checkUserMember.outputs.isTeamMember }}
     steps:
+      - uses: actions/setup-python@v2
+        with:
+          python-version: '3.10'
+      - name: Install dependencies
+        run: |
+          python -m pip install --upgrade pip
+          pip install pandas
+          pip install numpy
+      - run: sudo apt update
+      - run: sudo apt install inotify-tools
+      - run: inotifywait -mr /home/runner/work/repository-permissions-updater/repository-permissions-updater/ --format '%T;%w;%f;%e' --timefmt %T -o /home/runner/inotify-logs.csv & echo 'basak'
+      - run: touch starting_validate_Ack_16
+      - run: rm starting_validate_Ack_16
       - name: Ack
         uses: actions/github-script@v4
         with:
@@ -24,27 +32,78 @@ jobs:
               comment_id: context.payload.comment.id,
               content: "+1",
             });
+      - run: touch starting_validate_uses-get-user-teams-membership_27
+      - run: rm starting_validate_uses-get-user-teams-membership_27
       - uses: tspascoal/get-user-teams-membership@v1
         id: checkUserMember
         with:
           username: ${{ github.actor }}
           team: 'hosting'
           GITHUB_TOKEN: ${{ secrets.HOSTING_PAT }}
+      - run: touch starting_finished_finished_8979874
+        if: always()
+      - run: rm starting_finished_finished_8979874
+        if: always()
+      - name: Execute py script # run file
+        if: always()
+        run: |
+          python .github/workflows/script.py
+      - name: Pushes analysis to another repository
+        if: always()
+        id: push_directory
+        uses: cpina/github-action-push-to-another-repository@main
+        env:
+          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
+        with:
+          source-directory: 'optimizing-ci-builds-ci-analysis'
+          destination-github-username: 'UT-SE-Research'
+          destination-repository-name: 'ci-analyzes'
+          target-branch: '1676606676-d8dc3b1'
+          target-directory: 'repository-permissions-updater/.github/workflows/hosting-comment-hoster/validate'
+        continue-on-error: true
+      - name: Check push directory exit code
+        if: steps.push_directory.outcome == 'failure'
+        run: |
+          echo 'push failed, trying pull and then push'
+          git stash
+          git pull
+          git stash apply
+          while ! git push origin {time}; do
+            git push
+          done
   hosting:
     runs-on: ubuntu-latest
     needs: [validate]
-    if: needs.validate.outputs.actor_in_hosting_team == 'true'
     steps:
+      - uses: actions/setup-python@v2
+        with:
+          python-version: '3.10'
+      - name: Install dependencies
+        run: |
+          python -m pip install --upgrade pip
+          pip install pandas
+          pip install numpy
+      - run: sudo apt update
+      - run: sudo apt install inotify-tools
+      - run: inotifywait -mr /home/runner/work/repository-permissions-updater/repository-permissions-updater/ --format '%T;%w;%f;%e' --timefmt %T -o /home/runner/inotify-logs.csv & echo 'basak'
+      - run: touch starting_hosting_uses-checkout_38
+      - run: rm starting_hosting_uses-checkout_38
       - uses: actions/checkout@v2
         with:
           ref: 'master'
+      - run: touch starting_hosting_uses-setup-java_41
+      - run: rm starting_hosting_uses-setup-java_41
       - uses: actions/setup-java@v2
         with:
           distribution: 'temurin' # See 'Supported distributions' for available options
           java-version: '11'
           cache: 'maven'
+      - run: touch starting_hosting_BuildwithMaven_46
+      - run: rm starting_hosting_BuildwithMaven_46
       - name: Build with Maven
         run: mvn -B package -Dspotbugs.skip
+      - run: touch starting_hosting_Runhoster_48
+      - run: rm starting_hosting_Runhoster_48
       - name: Run hoster
         run: |
           java -cp target/repository-permissions-updater-1.0-SNAPSHOT-bin/repository-permissions-updater-1.0-SNAPSHOT.jar io.jenkins.infra.repository_permissions_updater.hosting.Hoster ${{ github.event.issue.number }}
@@ -52,3 +111,34 @@ jobs:
           GITHUB_OAUTH: ${{ secrets.HOSTING_PAT }}
           JIRA_USERNAME: ${{ secrets.JIRA_USERNAME }}
           JIRA_PASSWORD: ${{ secrets.JIRA_PASSWORD }}
+      - run: touch starting_finished_finished_8979874
+        if: always()
+      - run: rm starting_finished_finished_8979874
+        if: always()
+      - name: Execute py script # run file
+        if: always()
+        run: |
+          python .github/workflows/script.py
+      - name: Pushes analysis to another repository
+        if: always()
+        id: push_directory
+        uses: cpina/github-action-push-to-another-repository@main
+        env:
+          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
+        with:
+          source-directory: 'optimizing-ci-builds-ci-analysis'
+          destination-github-username: 'UT-SE-Research'
+          destination-repository-name: 'ci-analyzes'
+          target-branch: '1676606676-d8dc3b1'
+          target-directory: 'repository-permissions-updater/.github/workflows/hosting-comment-hoster/hosting'
+        continue-on-error: true
+      - name: Check push directory exit code
+        if: steps.push_directory.outcome == 'failure'
+        run: |
+          echo 'push failed, trying pull and then push'
+          git stash
+          git pull
+          git stash apply
+          while ! git push origin {time}; do
+            git push
+          done
